(ns run-length-encoding)

(defn run-length-encode [] ;; <--- argument goes here...
  ;; your code goes here...
  )

(defn run-length-decode [] ;; <--- argument goes here...
  ;; your code goes here...
  )
