name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1273.sh
          chmod +x linux-install-1.11.1.1273.sh
          sudo ./linux-install-1.11.1.1273.sh

      - name: Verify all exercises
        run: ./bin/verify-exercises
